
CREATE TABLE IF NOT EXISTS developers  (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY key,
	name	VARCHAR(30) NOT NULL,
	age	int NOT NULL,
	sex	VARCHAR(30) NOT NULL,
	salary int not null
);
CREATE TABLE IF NOT EXISTS skills (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY key,
	language	VARCHAR(30),
	level	VARCHAR(30)
);
CREATE TABLE IF NOT EXISTS projects  (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY key,
	project_name	VARCHAR(30),
	description	TEXT
);
CREATE TABLE IF NOT EXISTS customers (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY key,
	first_name	VARCHAR(30) NOT NULL,
	last_name	VARCHAR(30)
);
CREATE TABLE IF NOT EXISTS companies (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY key,
	company_name	VARCHAR(30) NOT NULL,
	quantity_employee	int
);
CREATE TABLE IF NOT EXISTS company_x_prj (
	company_id	INTEGER NOT NULL,
	project_id	INTEGER NOT NULL,
	FOREIGN KEY(project_id) REFERENCES projects (id),
	FOREIGN KEY(company_id) REFERENCES companies (id)
);
CREATE TABLE IF NOT EXISTS custom_x_prj (
	custom_id	INTEGER NOT NULL,
	project_id	INTEGER NOT NULL,
	FOREIGN KEY(project_id) REFERENCES projects (id),
	FOREIGN KEY(custom_id) REFERENCES customers (id)
);
CREATE TABLE IF NOT EXISTS dev_x_prj (
	developer_id	INTEGER NOT NULL,
	project_id	INTEGER NOT NULL,
	FOREIGN KEY(developer_id) REFERENCES developers (id),
	FOREIGN KEY(project_id) REFERENCES projects (id)
);
CREATE TABLE IF NOT EXISTS dev_x_skills (
	developer_id	INTEGER NOT NULL,
	skills_id	INTEGER NOT NULL,
	FOREIGN KEY(skills_id) REFERENCES skills (id),
	FOREIGN KEY(developer_id) REFERENCES developers (id)
);
